# Generated by Django 4.1.5 on 2023-02-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
