# Generated by Django 4.1.5 on 2023-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_test_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='test_1',
            field=models.BooleanField(),
        ),
    ]
