# Generated by Django 4.1.5 on 2023-03-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_test_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='test_1',
            field=models.BooleanField(default=False),
        ),
    ]
