# Generated by Django 4.1.5 on 2023-02-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=150)),
                ('q2', models.CharField(max_length=150)),
                ('q3', models.CharField(max_length=150)),
                ('q4', models.CharField(max_length=150)),
                ('q5', models.CharField(max_length=150)),
            ],
        ),
    ]
