# Generated by Django 4.1.5 on 2023-02-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_article_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
