# Generated by Django 4.1.5 on 2023-02-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
